{
    "kind": "Listing",
    "data": {
        "modhash": "0mmtb9rno9f6f6ae75c6dba96f507427c5205eccc74d8083e2",
        "dist": 25,
        "facets": {},
        "after": "t3_occxg4",
        "geo_filter": "",
        "children": [{
            "kind": "t3",
            "data": {
                "approved_at_utc": null,
                "subreddit": "aww",
                "selftext": "",
                "author_fullname": "t2_afxpg",
                "saved": false,
                "mod_reason_title": null,
                "gilded": 0,
                "clicked": false,
                "title": "Parrots consider this guy with a blue hat as one of their own",
                "link_flair_richtext": [],
                "subreddit_name_prefixed": "r/aww",
                "hidden": false,
                "pwls": 6,
                "link_flair_css_class": null,
                "downs": 0,
                "thumbnail_height": 140,
                "top_awarded_type": "INACTIVE",
                "hide_score": false,
                "name": "t3_nl9zjj",
                "quarantine": false,
                "link_flair_text_color": "dark",
                "upvote_ratio": 0.95,
                "author_flair_background_color": null,
                "subreddit_type": "public",
                "ups": 81000,
                "total_awards_received": 246,
                "media_embed": {
                    "content": "&lt;iframe class=\"embedly-embed\" src=\"https://cdn.embedly.com/widgets/media.html?src=https%3A%2F%2Fgfycat.com%2Fifr%2Femotionalremotegrouse&amp;display_name=Gfycat&amp;url=https%3A%2F%2Fgfycat.com%2Femotionalremotegrouse&amp;image=https%3A%2F%2Fthumbs.gfycat.com%2FEmotionalRemoteGrouse-size_restricted.gif&amp;key=ed8fa8699ce04833838e66ce79ba05f1&amp;type=text%2Fhtml&amp;schema=gfycat\" width=\"382\" height=\"600\" scrolling=\"no\" title=\"Gfycat embed\" frameborder=\"0\" allow=\"autoplay; fullscreen\" allowfullscreen=\"true\"&gt;&lt;/iframe&gt;",
                    "width": 382,
                    "scrolling": false,
                    "height": 600
                },
                "thumbnail_width": 140,
                "author_flair_template_id": null,
                "is_original_content": false,
                "user_reports": [],
                "secure_media": {
                    "type": "gfycat.com",
                    "oembed": {
                        "provider_url": "https://gfycat.com",
                        "description": "Watch and share Blue Own Moral Support GIFs by palifaith on Gfycat",
                        "title": "Blue own moral support",
                        "type": "video",
                        "author_name": "Gfycat",
                        "height": 600,
                        "width": 382,
                        "html": "&lt;iframe class=\"embedly-embed\" src=\"https://cdn.embedly.com/widgets/media.html?src=https%3A%2F%2Fgfycat.com%2Fifr%2Femotionalremotegrouse&amp;display_name=Gfycat&amp;url=https%3A%2F%2Fgfycat.com%2Femotionalremotegrouse&amp;image=https%3A%2F%2Fthumbs.gfycat.com%2FEmotionalRemoteGrouse-size_restricted.gif&amp;key=ed8fa8699ce04833838e66ce79ba05f1&amp;type=text%2Fhtml&amp;schema=gfycat\" width=\"382\" height=\"600\" scrolling=\"no\" title=\"Gfycat embed\" frameborder=\"0\" allow=\"autoplay; fullscreen\" allowfullscreen=\"true\"&gt;&lt;/iframe&gt;",
                        "thumbnail_width": 250,
                        "version": "1.0",
                        "provider_name": "Gfycat",
                        "thumbnail_url": "https://i.embed.ly/1/image?url=https%3A%2F%2Fthumbs.gfycat.com%2FEmotionalRemoteGrouse-size_restricted.gif&amp;key=ed8fa8699ce04833838e66ce79ba05f1",
                        "thumbnail_height": 392
                    }
                },
                "is_reddit_media_domain": false,
                "is_meta": false,
                "category": null,
                "secure_media_embed": {
                    "content": "&lt;iframe class=\"embedly-embed\" src=\"https://cdn.embedly.com/widgets/media.html?src=https%3A%2F%2Fgfycat.com%2Fifr%2Femotionalremotegrouse&amp;display_name=Gfycat&amp;url=https%3A%2F%2Fgfycat.com%2Femotionalremotegrouse&amp;image=https%3A%2F%2Fthumbs.gfycat.com%2FEmotionalRemoteGrouse-size_restricted.gif&amp;key=ed8fa8699ce04833838e66ce79ba05f1&amp;type=text%2Fhtml&amp;schema=gfycat\" width=\"382\" height=\"600\" scrolling=\"no\" title=\"Gfycat embed\" frameborder=\"0\" allow=\"autoplay; fullscreen\" allowfullscreen=\"true\"&gt;&lt;/iframe&gt;",
                    "width": 382,
                    "scrolling": false,
                    "media_domain_url": "https://www.redditmedia.com/mediaembed/nl9zjj",
                    "height": 600
                },
                "link_flair_text": null,
                "can_mod_post": false,
                "score": 81000,
                "approved_by": null,
                "is_created_from_ads_ui": false,
                "author_premium": true,
                "thumbnail": "https://b.thumbs.redditmedia.com/oxACJEe_yGx6beS0_omUteq1wSspNH_9JpskC4PxekY.jpg",
                "edited": false,
                "author_flair_css_class": null,
                "author_flair_richtext": [],
                "gildings": {
                    "gid_1": 52
                },
                "post_hint": "rich:video",
                "content_categories": null,
                "is_self": false,
                "mod_note": null,
                "created": 1622038672.0,
                "link_flair_type": "text",
                "wls": 6,
                "removed_by_category": null,
                "banned_by": null,
                "author_flair_type": "text",
                "domain": "gfycat.com",
                "allow_live_comments": true,
                "selftext_html": null,
                "likes": null,
                "suggested_sort": null,
                "banned_at_utc": null,
                "url_overridden_by_dest": "https://gfycat.com/emotionalremotegrouse",
                "view_count": null,
                "archived": false,
                "no_follow": false,
                "is_crosspostable": true,
                "pinned": false,
                "over_18": false,
                "preview": {
                    "images": [{
                        "source": {
                            "url": "https://external-preview.redd.it/MHufpB1ZhB72C09kRItIvtdiOTDxW3fl7dhPRlZHATc.jpg?auto=webp&amp;s=5ba8873720204ac12c9eabe907eedd7d21808424",
                            "width": 250,
                            "height": 392
                        },
                        "resolutions": [{
                            "url": "https://external-preview.redd.it/MHufpB1ZhB72C09kRItIvtdiOTDxW3fl7dhPRlZHATc.jpg?width=108&amp;crop=smart&amp;auto=webp&amp;s=69e7af8a0742bb1dee4c536f40afee7a1ab9061b",
                            "width": 108,
                            "height": 169
                        }, {
                            "url": "https://external-preview.redd.it/MHufpB1ZhB72C09kRItIvtdiOTDxW3fl7dhPRlZHATc.jpg?width=216&amp;crop=smart&amp;auto=webp&amp;s=c5ca803851881f89effa90f312fbeddc206d7c5e",
                            "width": 216,
                            "height": 338
                        }],
                        "variants": {},
                        "id": "kraud4Sq77BVJDEvKONSp6VxXAWobW-PG0MD2qpex98"
                    }],
                    "reddit_video_preview": {
                        "bitrate_kbps": 1200,
                        "fallback_url": "https://v.redd.it/g6x9vh2gpy271/DASH_480.mp4",
                        "height": 480,
                        "width": 305,
                        "scrubber_media_url": "https://v.redd.it/g6x9vh2gpy271/DASH_96.mp4",
                        "dash_url": "https://v.redd.it/g6x9vh2gpy271/DASHPlaylist.mpd",
                        "duration": 8,
                        "hls_url": "https://v.redd.it/g6x9vh2gpy271/HLSPlaylist.m3u8",
                        "is_gif": true,
                        "transcoding_status": "completed"
                    },
                    "enabled": false
                },
                "all_awardings": [{
                    "giver_coin_reward": null,
                    "subreddit_id": null,
                    "is_new": false,
                    "days_of_drip_extension": 0,
                    "coin_price": 500,
                    "id": "award_1f0462ee-18f5-4f33-89cf-f1f79336a452",
                    "penny_donate": null,
                    "award_sub_type": "GLOBAL",
                    "coin_reward": 100,
                    "icon_url": "https://i.redd.it/award_images/t5_22cerq/0o2j782f00e41_WholesomeSuperpro.png",
                    "days_of_premium": 0,
                    "tiers_by_required_awardings": null,
                    "resized_icons": [{
                        "url": "https://preview.redd.it/award_images/t5_22cerq/0o2j782f00e41_WholesomeSuperpro.png?width=16&amp;height=16&amp;auto=webp&amp;s=3ca7dc1f4e12ca386a561446e72f772d38ba49d8",
                        "width": 16,
                        "height": 16
                    }, {
                        "url": "https://preview.redd.it/award_images/t5_22cerq/0o2j782f00e41_WholesomeSuperpro.png?width=32&amp;height=32&amp;auto=webp&amp;s=c19d1e661e4aa6a9326a9f0b74b3ebf5d9f7a75e",
                        "width": 32,
                        "height": 32
                    }, {
                        "url": "https://preview.redd.it/award_images/t5_22cerq/0o2j782f00e41_WholesomeSuperpro.png?width=48&amp;height=48&amp;auto=webp&amp;s=ed063580825e72b0ae63fe30c807b453b1362694",
                        "width": 48,
                        "height": 48
                    }, {
                        "url": "https://preview.redd.it/award_images/t5_22cerq/0o2j782f00e41_WholesomeSuperpro.png?width=64&amp;height=64&amp;auto=webp&amp;s=7176b4b72b850e3e052138fe8b3967c4c5b52dae",
                        "width": 64,
                        "height": 64
                    }, {
                        "url": "https://preview.redd.it/award_images/t5_22cerq/0o2j782f00e41_WholesomeSuperpro.png?width=128&amp;height=128&amp;auto=webp&amp;s=f7b307840995777f9ae04699d019740658ba0e77",
                        "width": 128,
                        "height": 128
                    }],
                    "icon_width": 2048,
                    "static_icon_width": 2048,
                    "start_date": null,
                    "is_enabled": true,
                    "awardings_required_to_grant_benefits": null,
                    "description": "When you come across a feel-good thing. Gives %{coin_symbol}100 Coins to both the author and the community.",
                    "end_date": null,
                    "subreddit_coin_reward": 100,
                    "count": 1,
                    "static_icon_height": 2048,
                    "name": "Wholesome (Pro)",
                    "resized_static_icons": [{
                        "url": "https://preview.redd.it/award_images/t5_22cerq/0o2j782f00e41_WholesomeSuperpro.png?width=16&amp;height=16&amp;auto=webp&amp;s=3ca7dc1f4e12ca386a561446e72f772d38ba49d8",
                        "width": 16,
                        "height": 16
                    }, {
                        "url": "https://preview.redd.it/award_images/t5_22cerq/0o2j782f00e41_WholesomeSuperpro.png?width=32&amp;height=32&amp;auto=webp&amp;s=c19d1e661e4aa6a9326a9f0b74b3ebf5d9f7a75e",
                        "width": 32,
                        "height": 32
                    }, {
                        "url": "https://preview.redd.it/award_images/t5_22cerq/0o2j782f00e41_WholesomeSuperpro.png?width=48&amp;height=48&amp;auto=webp&amp;s=ed063580825e72b0ae63fe30c807b453b1362694",
                        "width": 48,
                        "height": 48
                    }, {
                        "url": "https://preview.redd.it/award_images/t5_22cerq/0o2j782f00e41_WholesomeSuperpro.png?width=64&amp;height=64&amp;auto=webp&amp;s=7176b4b72b850e3e052138fe8b3967c4c5b52dae",
                        "width": 64,
                        "height": 64
                    }, {
                        "url": "https://preview.redd.it/award_images/t5_22cerq/0o2j782f00e41_WholesomeSuperpro.png?width=128&amp;height=128&amp;auto=webp&amp;s=f7b307840995777f9ae04699d019740658ba0e77",
                        "width": 128,
                        "height": 128
                    }],
                    "icon_format": null,
                    "icon_height": 2048,
                    "penny_price": null,
                    "award_type": "global",
                    "static_icon_url": "https://i.redd.it/award_images/t5_22cerq/0o2j782f00e41_WholesomeSuperpro.png"
                }, {
                    "giver_coin_reward": null,
                    "subreddit_id": null,
                    "is_new": false,
                    "days_of_drip_extension": 0,
                    "coin_price": 500,
                    "id": "award_43c43a35-15c5-4f73-91ef-fe538426435a",
                    "penny_donate": null,
                    "award_sub_type": "GLOBAL",
                    "coin_reward": 100,
                    "icon_url": "https://i.redd.it/award_images/t5_22cerq/xe5mw55w5v541_BlessUp.png",
                    "days_of_premium": 0,
                    "tiers_by_required_awardings": null,
                    "resized_icons": [{
                        "url": "https://preview.redd.it/award_images/t5_22cerq/xe5mw55w5v541_BlessUp.png?width=16&amp;height=16&amp;auto=webp&amp;s=e84e08de4b1352e679d612c063584341f56bc2b5",
                        "width": 16,
                        "height": 16
                    }, {
                        "url": "https://preview.redd.it/award_images/t5_22cerq/xe5mw55w5v541_BlessUp.png?width=32&amp;height=32&amp;auto=webp&amp;s=d01d7a3286bb55c235e217736c78c66e2d7d0c18",
                        "width": 32,
                        "height": 32
                    }, {
                        "url": "https://preview.redd.it/award_images/t5_22cerq/xe5mw55w5v541_BlessUp.png?width=48&amp;height=48&amp;auto=webp&amp;s=6ae7d390be614e44f1ec06141d0ba51d65494bff",
                        "width": 48,
                        "height": 48
                    }, {
                        "url": "https://preview.redd.it/award_images/t5_22cerq/xe5mw55w5v541_BlessUp.png?width=64&amp;height=64&amp;auto=webp&amp;s=1c88befd3d95c2ea37b95a7132db98d8a8730ae1",
                        "width": 64,
                        "height": 64
                    }, {
                        "url": "https://preview.redd.it/award_images/t5_22cerq/xe5mw55w5v541_BlessUp.png?width=128&amp;height=128&amp;auto=webp&amp;s=f97d6987f6545f6cb659f1fce7c304278a92f762",
                        "width": 128,
                        "height": 128
                    }],
                    "icon_width": 2048,
                    "static_icon_width": 2048,
                    "start_date": null,
                    "is_enabled": true,
                    "awardings_required_to_grant_benefits": null,
                    "description": "Prayers up for the blessed. Gives %{coin_symbol}100 Coins to both the author and the community.",
                    "end_date": null,
                    "subreddit_coin_reward": 100,
                    "count": 1,
                    "static_icon_height": 2048,
                    "name": "Bless Up (Pro)",
                    "resized_static_icons": [{
                        "url": "https://preview.redd.it/award_images/t5_22cerq/xe5mw55w5v541_BlessUp.png?width=16&amp;height=16&amp;auto=webp&amp;s=e84e08de4b1352e679d612c063584341f56bc2b5",
                        "width": 16,
                        "height": 16
                    }, {
                        "url": "https://preview.redd.it/award_images/t5_22cerq/xe5mw55w5v541_BlessUp.png?width=32&amp;height=32&amp;auto=webp&amp;s=d01d7a3286bb55c235e217736c78c66e2d7d0c18",
                        "width": 32,
                        "height": 32
                    }, {
                        "url": "https://preview.redd.it/award_images/t5_22cerq/xe5mw55w5v541_BlessUp.png?width=48&amp;height=48&amp;auto=webp&amp;s=6ae7d390be614e44f1ec06141d0ba51d65494bff",
                        "width": 48,
                        "height": 48
                    }, {
                        "url": "https://preview.redd.it/award_images/t5_22cerq/xe5mw55w5v541_BlessUp.png?width=64&amp;height=64&amp;auto=webp&amp;s=1c88befd3d95c2ea37b95a7132db98d8a8730ae1",
                        "width": 64,
                        "height": 64
                    }, {
                        "url": "https://preview.redd.it/award_images/t5_22cerq/xe5mw55w5v541_BlessUp.png?width=128&amp;height=128&amp;auto=webp&amp;s=f97d6987f6545f6cb659f1fce7c304278a92f762",
                        "width": 128,
                        "height": 128
                    }],
                    "icon_format": null,
                    "icon_height": 2048,
                    "penny_price": null,
                    "award_type": "global",
                    "static_icon_url": "https://i.redd.it/award_images/t5_22cerq/xe5mw55w5v541_BlessUp.png"
                }, {
                    "giver_coin_reward": 0,
                    "subreddit_id": null,
                    "is_new": false,
                    "days_of_drip_extension": 0,
                    "coin_price": 325,
                    "id": "award_6220ecfe-4552-4949-aa13-fb1fb7db537c",
                    "penny_donate": 0,
                    "award_sub_type": "GLOBAL",
                    "coin_reward": 0,
                    "icon_url": "https://www.redditstatic.com/gold/awards/icon/Superheart_512.png",
                    "days_of_premium": 0,
                    "tiers_by_required_awardings": null,
                    "resized_icons": [{
                        "url": "https://www.redditstatic.com/gold/awards/icon/Superheart_16.png",
                        "width": 16,
                        "height": 16
                    }, {
                        "url": "https://www.redditstatic.com/gold/awards/icon/Superheart_32.png",
                        "width": 32,
                        "height": 32
                    }, {
                        "url": "https://www.redditstatic.com/gold/awards/icon/Superheart_48.png",
                        "width": 48,
                        "height": 48
                    }, {
                        "url": "https://www.redditstatic.com/gold/awards/icon/Superheart_64.png",
                        "width": 64,
                        "height": 64
                    }, {
                        "url": "https://www.redditstatic.com/gold/awards/icon/Superheart_128.png",
                        "width": 128,
                        "height": 128
                    }],
                    "icon_width": 512,
                    "static_icon_width": 512,
                    "start_date": null,
                    "is_enabled": true,
                    "awardings_required_to_grant_benefits": null,
                    "description": "When the love is out of control.",
                    "end_date": null,
                    "subreddit_coin_reward": 0,
                    "count": 1,
                    "static_icon_height": 512,
                    "name": "Super Heart Eyes",
                    "resized_static_icons": [{
                        "url": "https://external-preview.redd.it?width=16&amp;height=16&amp;auto=webp&amp;s=d88c9a453f8ac38850b7a8241cfe5804b7b4905d",
                        "width": 16,
                        "height": 16
                    }, {
                        "url": "https://external-preview.redd.it?width=32&amp;height=32&amp;auto=webp&amp;s=96a25019eb75878bdec4f6c012540f3baffbb1b2",
                        "width": 32,
                        "height": 32
                    }, {
                        "url": "https://external-preview.redd.it?width=48&amp;height=48&amp;auto=webp&amp;s=1a51d27d75afde3fbde8bba84f9338f511211461",
                        "width": 48,
                        "height": 48
                    }, {
                        "url": "https://external-preview.redd.it?width=64&amp;height=64&amp;auto=webp&amp;s=96af5ec460b05669ed60224cb0619bb8884abe27",
                        "width": 64,
                        "height": 64
                    }, {
                        "url": "https://external-preview.redd.it?width=128&amp;height=128&amp;auto=webp&amp;s=2d3e648ed2302e6258673051ca5291f57beb29d4",
                        "width": 128,
                        "height": 128
                    }],
                    "icon_format": "APNG",
                    "icon_height": 512,
                    "penny_price": 0,
                    "award_type": "global",
                    "static_icon_url": "https://www.redditstatic.com/gold/awards/icon/Superheart_512.png"
                }, {
                    "giver_coin_reward": null,
                    "subreddit_id": null,
                    "is_new": false,
                    "days_of_drip_extension": 0,
                    "coin_price": 150,
                    "id": "award_f44611f1-b89e-46dc-97fe-892280b13b82",
                    "penny_donate": null,
                    "award_sub_type": "GLOBAL",
                    "coin_reward": 0,
                    "icon_url": "https://i.redd.it/award_images/t5_22cerq/klvxk1wggfd41_Helpful.png",
                    "days_of_premium": 0,
                    "tiers_by_required_awardings": null,
                    "resized_icons": [{
                        "url": "https://preview.redd.it/award_images/t5_22cerq/klvxk1wggfd41_Helpful.png?width=16&amp;height=16&amp;auto=webp&amp;s=a5662dfbdb402bf67866c050aa76c31c147c2f45",
                        "width": 16,
                        "height": 16
                    }, {
                        "url": "https://preview.redd.it/award_images/t5_22cerq/klvxk1wggfd41_Helpful.png?width=32&amp;height=32&amp;auto=webp&amp;s=a6882eb3f380e8e88009789f4d0072e17b8c59f1",
                        "width": 32,
                        "height": 32
                    }, {
                        "url": "https://preview.redd.it/award_images/t5_22cerq/klvxk1wggfd41_Helpful.png?width=48&amp;height=48&amp;auto=webp&amp;s=e50064b090879e8a0b55e433f6ee61d5cb5fbe1d",
                        "width": 48,
                        "height": 48
                    }, {
                        "url": "https://preview.redd.it/award_images/t5_22cerq/klvxk1wggfd41_Helpful.png?width=64&amp;height=64&amp;auto=webp&amp;s=8e5bb2e76683cb6b161830bcdd9642049d6adc11",
                        "width": 64,
                        "height": 64
                    }, {
                        "url": "https://preview.redd.it/award_images/t5_22cerq/klvxk1wggfd41_Helpful.png?width=128&amp;height=128&amp;auto=webp&amp;s=eda4a9246f95f42ee6940cc0ec65306fd20de878",
                        "width": 128,
                        "height": 128
                    }],
                    "icon_width": 2048,
                    "static_icon_width": 2048,
                    "start_date": null,
                    "is_enabled": true,
                    "awardings_required_to_grant_benefits": null,
                    "description": "Thank you stranger. Shows the award.",
                    "end_date": null,
                    "subreddit_coin_reward": 0,
                    "count": 43,
                    "static_icon_height": 2048,
                    "name": "Helpful",
                    "resized_static_icons": [{
                        "url": "https://preview.redd.it/award_images/t5_22cerq/klvxk1wggfd41_Helpful.png?width=16&amp;height=16&amp;auto=webp&amp;s=a5662dfbdb402bf67866c050aa76c31c147c2f45",
                        "width": 16,
                        "height": 16
                    }, {
                        "url": "https://preview.redd.it/award_images/t5_22cerq/klvxk1wggfd41_Helpful.png?width=32&amp;height=32&amp;auto=webp&amp;s=a6882eb3f380e8e88009789f4d0072e17b8c59f1",
                        "width": 32,
                        "height": 32
                    }, {
                        "url": "https://preview.redd.it/award_images/t5_22cerq/klvxk1wggfd41_Helpful.png?width=48&amp;height=48&amp;auto=webp&amp;s=e50064b090879e8a0b55e433f6ee61d5cb5fbe1d",
                        "width": 48,
                        "height": 48
                    }, {
                        "url": "https://preview.redd.it/award_images/t5_22cerq/klvxk1wggfd41_Helpful.png?width=64&amp;height=64&amp;auto=webp&amp;s=8e5bb2e76683cb6b161830bcdd9642049d6adc11",
                        "width": 64,
                        "height": 64
                    }, {
                        "url": "https://preview.redd.it/award_images/t5_22cerq/klvxk1wggfd41_Helpful.png?width=128&amp;height=128&amp;auto=webp&amp;s=eda4a9246f95f42ee6940cc0ec65306fd20de878",
                        "width": 128,
                        "height": 128
                    }],
                    "icon_format": null,
                    "icon_height": 2048,
                    "penny_price": null,
                    "award_type": "global",
                    "static_icon_url": "https://i.redd.it/award_images/t5_22cerq/klvxk1wggfd41_Helpful.png"
                }, {
                    "giver_coin_reward": null,
                    "subreddit_id": null,
                    "is_new": false,
                    "days_of_drip_extension": 0,
                    "coin_price": 125,
                    "id": "award_5f123e3d-4f48-42f4-9c11-e98b566d5897",
                    "penny_donate": null,
                    "award_sub_type": "GLOBAL",
                    "coin_reward": 0,
                    "icon_url": "https://i.redd.it/award_images/t5_22cerq/5izbv4fn0md41_Wholesome.png",
                    "days_of_premium": 0,
                    "tiers_by_required_awardings": null,
                    "resized_icons": [{
                        "url": "https://preview.redd.it/award_images/t5_22cerq/5izbv4fn0md41_Wholesome.png?width=16&amp;height=16&amp;auto=webp&amp;s=92932f465d58e4c16b12b6eac4ca07d27e3d11c0",
                        "width": 16,
                        "height": 16
                    }, {
                        "url": "https://preview.redd.it/award_images/t5_22cerq/5izbv4fn0md41_Wholesome.png?width=32&amp;height=32&amp;auto=webp&amp;s=d11484a208d68a318bf9d4fcf371171a1cb6a7ef",
                        "width": 32,
                        "height": 32
                    }, {
                        "url": "https://preview.redd.it/award_images/t5_22cerq/5izbv4fn0md41_Wholesome.png?width=48&amp;height=48&amp;auto=webp&amp;s=febdf28b6f39f7da7eb1365325b85e0bb49a9f63",
                        "width": 48,
                        "height": 48
                    }, {
                        "url": "https://preview.redd.it/award_images/t5_22cerq/5izbv4fn0md41_Wholesome.png?width=64&amp;height=64&amp;auto=webp&amp;s=b4406a2d88bf86fa3dc8a45aacf7e0c7bdccc4fb",
                        "width": 64,
                        "height": 64
                    }, {
                        "url": "https://preview.redd.it/award_images/t5_22cerq/5izbv4fn0md41_Wholesome.png?width=128&amp;height=128&amp;auto=webp&amp;s=19555b13e3e196b62eeb9160d1ac1d1b372dcb0b",
                        "width": 128,
                        "height": 128
                    }],
                    "icon_width": 2048,
                    "static_icon_width": 2048,
                    "start_date": null,
                    "is_enabled": true,
                    "awardings_required_to_grant_benefits": null,
                    "description": "When you come across a feel-good thing.",
                    "end_date": null,
                    "subreddit_coin_reward": 0,
                    "count": 64,
                    "static_icon_height": 2048,
                    "name": "Wholesome",
                    "resized_static_icons": [{
                        "url": "https://preview.redd.it/award_images/t5_22cerq/5izbv4fn0md41_Wholesome.png?width=16&amp;height=16&amp;auto=webp&amp;s=92932f465d58e4c16b12b6eac4ca07d27e3d11c0",
                        "width": 16,
                        "height": 16
                    }, {
                        "url": "https://preview.redd.it/award_images/t5_22cerq/5izbv4fn0md41_Wholesome.png?width=32&amp;height=32&amp;auto=webp&amp;s=d11484a208d68a318bf9d4fcf371171a1cb6a7ef",
                        "width": 32,
                        "height": 32
                    }, {
                        "url": "https://preview.redd.it/award_images/t5_22cerq/5izbv4fn0md41_Wholesome.png?width=48&amp;height=48&amp;auto=webp&amp;s=febdf28b6f39f7da7eb1365325b85e0bb49a9f63",
                        "width": 48,
                        "height": 48
                    }, {
                        "url": "https://preview.redd.it/award_images/t5_22cerq/5izbv4fn0md41_Wholesome.png?width=64&amp;height=64&amp;auto=webp&amp;s=b4406a2d88bf86fa3dc8a45aacf7e0c7bdccc4fb",
                        "width": 64,
                        "height": 64
                    }, {
                        "url": "https://preview.redd.it/award_images/t5_22cerq/5izbv4fn0md41_Wholesome.png?width=128&amp;height=128&amp;auto=webp&amp;s=19555b13e3e196b62eeb9160d1ac1d1b372dcb0b",
                        "width": 128,
                        "height": 128
                    }],
                    "icon_format": null,
                    "icon_height": 2048,
                    "penny_price": null,
                    "award_type": "global",
                    "static_icon_url": "https://i.redd.it/award_images/t5_22cerq/5izbv4fn0md41_Wholesome.png"
                }, {
                    "giver_coin_reward": null,
                    "subreddit_id": null,
                    "is_new": false,
                    "days_of_drip_extension": 0,
                    "coin_price": 100,
                    "id": "gid_1",
                    "penny_donate": null,
                    "award_sub_type": "GLOBAL",
                    "coin_reward": 0,
                    "icon_url": "https://www.redditstatic.com/gold/awards/icon/silver_512.png",
                    "days_of_premium": 0,
                    "tiers_by_required_awardings": null,
                    "resized_icons": [{
                        "url": "https://www.redditstatic.com/gold/awards/icon/silver_16.png",
                        "width": 16,
                        "height": 16
                    }, {
                        "url": "https://www.redditstatic.com/gold/awards/icon/silver_32.png",
                        "width": 32,
                        "height": 32
                    }, {
                        "url": "https://www.redditstatic.com/gold/awards/icon/silver_48.png",
                        "width": 48,
                        "height": 48
                    }, {
                        "url": "https://www.redditstatic.com/gold/awards/icon/silver_64.png",
                        "width": 64,
                        "height": 64
                    }, {
                        "url": "https://www.redditstatic.com/gold/awards/icon/silver_128.png",
                        "width": 128,
                        "height": 128
                    }],
                    "icon_width": 512,
                    "static_icon_width": 512,
                    "start_date": null,
                    "is_enabled": true,
                    "awardings_required_to_grant_benefits": null,
                    "description": "Shows the Silver Award... and that's it.",
                    "end_date": null,
                    "subreddit_coin_reward": 0,
                    "count": 52,
                    "static_icon_height": 512,
                    "name": "Silver",
                    "resized_static_icons": [{
                        "url": "https://www.redditstatic.com/gold/awards/icon/silver_16.png",
                        "width": 16,
                        "height": 16
                    }, {
                        "url": "https://www.redditstatic.com/gold/awards/icon/silver_32.png",
                        "width": 32,
                        "height": 32
                    }, {
                        "url": "https://www.redditstatic.com/gold/awards/icon/silver_48.png",
                        "width": 48,
                        "height": 48
                    }, {
                        "url": "https://www.redditstatic.com/gold/awards/icon/silver_64.png",
                        "width": 64,
                        "height": 64
                    }, {
                        "url": "https://www.redditstatic.com/gold/awards/icon/silver_128.png",
                        "width": 128,
                        "height": 128
                    }],
                    "icon_format": null,
                    "icon_height": 512,
                    "penny_price": null,
                    "award_type": "global",
                    "static_icon_url": "https://www.redditstatic.com/gold/awards/icon/silver_512.png"
                }, {
                    "giver_coin_reward": 0,
                    "subreddit_id": null,
                    "is_new": false,
                    "days_of_drip_extension": 0,
                    "coin_price": 100,
                    "id": "award_19860e30-3331-4bac-b3d1-bd28de0c7974",
                    "penny_donate": 0,
                    "award_sub_type": "GLOBAL",
                    "coin_reward": 0,
                    "icon_url": "https://i.redd.it/award_images/t5_22cerq/v1mxw8i6wnf51_Heartwarming.png",
                    "days_of_premium": 0,
                    "tiers_by_required_awardings": null,
                    "resized_icons": [{
                        "url": "https://preview.redd.it/award_images/t5_22cerq/v1mxw8i6wnf51_Heartwarming.png?width=16&amp;height=16&amp;auto=webp&amp;s=4e50438bd2d72ae5398e839ac2bdcccf323fca79",
                        "width": 16,
                        "height": 16
                    }, {
                        "url": "https://preview.redd.it/award_images/t5_22cerq/v1mxw8i6wnf51_Heartwarming.png?width=32&amp;height=32&amp;auto=webp&amp;s=e730f68de038499700c6301470812c29ef6a8555",
                        "width": 32,
                        "height": 32
                    }, {
                        "url": "https://preview.redd.it/award_images/t5_22cerq/v1mxw8i6wnf51_Heartwarming.png?width=48&amp;height=48&amp;auto=webp&amp;s=8d7c7fa22e6ff3b1b0a347839e42f493eb5f6cbc",
                        "width": 48,
                        "height": 48
                    }, {
                        "url": "https://preview.redd.it/award_images/t5_22cerq/v1mxw8i6wnf51_Heartwarming.png?width=64&amp;height=64&amp;auto=webp&amp;s=11ec2a72e2724017bb8479639edce8a7f2ba64f4",
                        "width": 64,
                        "height": 64
                    }, {
                        "url": "https://preview.redd.it/award_images/t5_22cerq/v1mxw8i6wnf51_Heartwarming.png?width=128&amp;height=128&amp;auto=webp&amp;s=1e936ae571e89abb5a5aaa2efd2d7cfb0ed1b537",
                        "width": 128,
                        "height": 128
                    }],
                    "icon_width": 2048,
                    "static_icon_width": 2048,
                    "start_date": null,
                    "is_enabled": true,
                    "awardings_required_to_grant_benefits": null,
                    "description": "I needed this today",
                    "end_date": null,
                    "subreddit_coin_reward": 0,
                    "count": 1,
                    "static_icon_height": 2048,
                    "name": "Heartwarming",
                    "resized_static_icons": [{
                        "url": "https://preview.redd.it/award_images/t5_22cerq/v1mxw8i6wnf51_Heartwarming.png?width=16&amp;height=16&amp;auto=webp&amp;s=4e50438bd2d72ae5398e839ac2bdcccf323fca79",
                        "width": 16,
                        "height": 16
                    }, {
                        "url": "https://preview.redd.it/award_images/t5_22cerq/v1mxw8i6wnf51_Heartwarming.png?width=32&amp;height=32&amp;auto=webp&amp;s=e730f68de038499700c6301470812c29ef6a8555",
                        "width": 32,
                        "height": 32
                    }, {
                        "url": "https://preview.redd.it/award_images/t5_22cerq/v1mxw8i6wnf51_Heartwarming.png?width=48&amp;height=48&amp;auto=webp&amp;s=8d7c7fa22e6ff3b1b0a347839e42f493eb5f6cbc",
                        "width": 48,
                        "height": 48
                    }, {
                        "url": "https://preview.redd.it/award_images/t5_22cerq/v1mxw8i6wnf51_Heartwarming.png?width=64&amp;height=64&amp;auto=webp&amp;s=11ec2a72e2724017bb8479639edce8a7f2ba64f4",
                        "width": 64,
                        "height": 64
                    }, {
                        "url": "https://preview.redd.it/award_images/t5_22cerq/v1mxw8i6wnf51_Heartwarming.png?width=128&amp;height=128&amp;auto=webp&amp;s=1e936ae571e89abb5a5aaa2efd2d7cfb0ed1b537",
                        "width": 128,
                        "height": 128
                    }],
                    "icon_format": "PNG",
                    "icon_height": 2048,
                    "penny_price": 0,
                    "award_type": "global",
                    "static_icon_url": "https://i.redd.it/award_images/t5_22cerq/v1mxw8i6wnf51_Heartwarming.png"
                }, {
                    "giver_coin_reward": 0,
                    "subreddit_id": null,
                    "is_new": false,
                    "days_of_drip_extension": 0,
                    "coin_price": 80,
                    "id": "award_8352bdff-3e03-4189-8a08-82501dd8f835",
                    "penny_donate": 0,
                    "award_sub_type": "GLOBAL",
                    "coin_reward": 0,
                    "icon_url": "https://i.redd.it/award_images/t5_q0gj4/ks45ij6w05f61_oldHugz.png",
                    "days_of_premium": 0,
                    "tiers_by_required_awardings": null,
                    "resized_icons": [{
                        "url": "https://preview.redd.it/award_images/t5_q0gj4/ks45ij6w05f61_oldHugz.png?width=16&amp;height=16&amp;auto=webp&amp;s=73a23bf7f08b633508dedf457f2704c522b94a04",
                        "width": 16,
                        "height": 16
                    }, {
                        "url": "https://preview.redd.it/award_images/t5_q0gj4/ks45ij6w05f61_oldHugz.png?width=32&amp;height=32&amp;auto=webp&amp;s=50f2f16e71d2929e3d7275060af3ad6b851dbfb1",
                        "width": 32,
                        "height": 32
                    }, {
                        "url": "https://preview.redd.it/award_images/t5_q0gj4/ks45ij6w05f61_oldHugz.png?width=48&amp;height=48&amp;auto=webp&amp;s=ca487311563425e195699a4d7e4c57a98cbfde8b",
                        "width": 48,
                        "height": 48
                    }, {
                        "url": "https://preview.redd.it/award_images/t5_q0gj4/ks45ij6w05f61_oldHugz.png?width=64&amp;height=64&amp;auto=webp&amp;s=7b4eedcffb1c09a826e7837532c52979760f1d2b",
                        "width": 64,
                        "height": 64
                    }, {
                        "url": "https://preview.redd.it/award_images/t5_q0gj4/ks45ij6w05f61_oldHugz.png?width=128&amp;height=128&amp;auto=webp&amp;s=e4d5ab237eb71a9f02bb3bf9ad5ee43741918d6c",
                        "width": 128,
                        "height": 128
                    }],
                    "icon_width": 2048,
                    "static_icon_width": 2048,
                    "start_date": null,
                    "is_enabled": true,
                    "awardings_required_to_grant_benefits": null,
                    "description": "Everything is better with a good hug",
                    "end_date": null,
                    "subreddit_coin_reward": 0,
                    "count": 83,
                    "static_icon_height": 2048,
                    "name": "Hugz",
                    "resized_static_icons": [{
                        "url": "https://preview.redd.it/award_images/t5_q0gj4/fpm0r5ryq1361_PolarHugs.png?width=16&amp;height=16&amp;auto=webp&amp;s=69997ace3ef4ffc099b81d774c2c8f1530602875",
                        "width": 16,
                        "height": 16
                    }, {
                        "url": "https://preview.redd.it/award_images/t5_q0gj4/fpm0r5ryq1361_PolarHugs.png?width=32&amp;height=32&amp;auto=webp&amp;s=e9519d1999ef9dce5c8a9f59369cb92f52d95319",
                        "width": 32,
                        "height": 32
                    }, {
                        "url": "https://preview.redd.it/award_images/t5_q0gj4/fpm0r5ryq1361_PolarHugs.png?width=48&amp;height=48&amp;auto=webp&amp;s=f076c6434fb2d2f9075991810fd845c40fa73fc6",
                        "width": 48,
                        "height": 48
                    }, {
                        "url": "https://preview.redd.it/award_images/t5_q0gj4/fpm0r5ryq1361_PolarHugs.png?width=64&amp;height=64&amp;auto=webp&amp;s=85527145e0c4b754306a30df29e584fd16187636",
                        "width": 64,
                        "height": 64
                    }, {
                        "url": "https://preview.redd.it/award_images/t5_q0gj4/fpm0r5ryq1361_PolarHugs.png?width=128&amp;height=128&amp;auto=webp&amp;s=b8843cdf82c3b741d7af057c14076dcd2621e811",
                        "width": 128,
                        "height": 128
                    }],
                    "icon_format": "PNG",
                    "icon_height": 2048,
                    "penny_price": 0,
                    "award_type": "global",
                    "static_icon_url": "https://i.redd.it/award_images/t5_q0gj4/fpm0r5ryq1361_PolarHugs.png"
                }],
                "awarders": [],
                "media_only": false,
                "can_gild": true,
                "spoiler": false,
                "locked": false,
                "author_flair_text": null,
                "treatment_tags": [],
                "visited": false,
                "removed_by": null,
                "num_reports": null,
                "distinguished": null,
                "subreddit_id": "t5_2qh1o",
                "mod_reason_by": null,
                "removal_reason": null,
                "link_flair_background_color": "",
                "id": "nl9zjj",
                "is_robot_indexable": true,
                "report_reasons": null,
                "author": "Palifaith",
                "discussion_type": null,
                "num_comments": 1204,
                "send_replies": true,
                "whitelist_status": "all_ads",
                "contest_mode": false,
                "mod_reports": [],
                "author_patreon_flair": false,
                "author_flair_text_color": null,
                "permalink": "/r/aww/comments/nl9zjj/parrots_consider_this_guy_with_a_blue_hat_as_one/",
                "parent_whitelist_status": "all_ads",
                "stickied": false,
                "url": "https://gfycat.com/emotionalremotegrouse",
                "subreddit_subscribers": 28912312,
                "created_utc": 1622009872.0,
                "num_crossposts": 17,
                "media": {
                    "type": "gfycat.com",
                    "oembed": {
                        "provider_url": "https://gfycat.com",
                        "description": "Watch and share Blue Own Moral Support GIFs by palifaith on Gfycat",
                        "title": "Blue own moral support",
                        "type": "video",
                        "author_name": "Gfycat",
                        "height": 600,
                        "width": 382,
                        "html": "&lt;iframe class=\"embedly-embed\" src=\"https://cdn.embedly.com/widgets/media.html?src=https%3A%2F%2Fgfycat.com%2Fifr%2Femotionalremotegrouse&amp;display_name=Gfycat&amp;url=https%3A%2F%2Fgfycat.com%2Femotionalremotegrouse&amp;image=https%3A%2F%2Fthumbs.gfycat.com%2FEmotionalRemoteGrouse-size_restricted.gif&amp;key=ed8fa8699ce04833838e66ce79ba05f1&amp;type=text%2Fhtml&amp;schema=gfycat\" width=\"382\" height=\"600\" scrolling=\"no\" title=\"Gfycat embed\" frameborder=\"0\" allow=\"autoplay; fullscreen\" allowfullscreen=\"true\"&gt;&lt;/iframe&gt;",
                        "thumbnail_width": 250,
                        "version": "1.0",
                        "provider_name": "Gfycat",
                        "thumbnail_url": "https://i.embed.ly/1/image?url=https%3A%2F%2Fthumbs.gfycat.com%2FEmotionalRemoteGrouse-size_restricted.gif&amp;key=ed8fa8699ce04833838e66ce79ba05f1",
                        "thumbnail_height": 392
                    }
                },
                "is_video": false
            }
        }, {
            